### ISSUE TITLE
Add support for position, rotation, and scale

### ISSUE THREAD

**Issue by MacNDyl** [Daw588/vanita#10]
[ { "code": "invalid_type", "expected": "number", "received": "undefined", "path": [ "character", "assets", 11, "meta", "order" ], "message": "Required" }, { "code": "unrecognized_keys", "keys": [ "position", "rotation", "scale" ], "path": [ "character", "assets", 11, "meta" ], "message": "Unrecognized key(s) in object: 'position', 'rotation', 'scale'" }, { "code": "invalid_type", "expected": "number", "received": "undefined", "path": [ "character", "assets", 12, "meta", "order" ], "message": "Required" }, { "code": "unrecognized_keys", "keys": [ "position", "rotation", "scale" ], "path": [ "character", "assets", 12, "meta" ], "message": "Unrecognized key(s) in object: 'position', 'rotation', 'scale'" }, { "code": "invalid_type", "expected": "number", "received": "undefined", "path": [ "character", "assets", 14, "meta", "order" ], "message": "Required" }, { "code": "unrecognized_keys", "keys": [ "position", "rotation", "scale" ], "path": [ "character", "assets", 14, "meta" ], "message": "Unrecognized key(s) in object: 'position', 'rotation', 'scale'" }, { "code": "invalid_type", "expected": "number", "received": "undefined", "path": [ "character", "assets", 29, "meta", "order" ], "message": "Required" }, { "code": "unrecognized_keys", "keys": [ "position", "rotation", "scale" ], "path": [ "character", "assets", 29, "meta" ], "message": "Unrecognized key(s) in object: 'position', 'rotation', 'scale'" } ]

**Comment by Daw588** [comment]
Support for the position, rotation, and scale is underway. I will let you know once the update is out.
